"""initial helios phase 1 schema

Revision ID: 482380a47455
Revises:
Create Date: 2026-07-25 21:12:05.823532+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision: str = "482380a47455"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "human_reviews",
        sa.Column("target_table", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("previous_status", sa.String(length=30), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_reviews")),
    )
    op.create_index(
        "ix_human_reviews_target", "human_reviews", ["target_table", "target_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_reviews_target_id"), "human_reviews", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_reviews_target_table"), "human_reviews", ["target_table"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("model_kind", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parameters_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("calibration_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("name", "version", name="model_version_unique"),
    )
    op.create_table(
        "organizations",
        sa.Column("canonical_name", sa.String(length=400), nullable=False),
        sa.Column("normalized_name", sa.String(length=400), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("organization_type", sa.String(length=60), nullable=True),
        sa.Column("is_natural_person", sa.Boolean(), nullable=False),
        sa.Column("is_redacted", sa.Boolean(), nullable=False),
        sa.Column("is_suspected_shell", sa.Boolean(), nullable=False),
        sa.Column("shell_indicators", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("jurisdiction_of_formation", sa.String(length=80), nullable=True),
        sa.Column("registry_id", sa.String(length=120), nullable=True),
        sa.Column("formation_date", sa.Date(), nullable=True),
        sa.Column("mailing_address", sa.Text(), nullable=True),
        sa.Column("mailing_city", sa.String(length=120), nullable=True),
        sa.Column("mailing_state", sa.String(length=40), nullable=True),
        sa.Column("mailing_postal_code", sa.String(length=20), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations_canonical_name"), "organizations", ["canonical_name"], unique=False
    )
    op.create_index(
        "ix_organizations_name_trgm",
        "organizations",
        ["normalized_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized_name": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_organizations_normalized_name"), "organizations", ["normalized_name"], unique=False
    )
    op.create_index(
        "ix_organizations_normalized_role",
        "organizations",
        ["normalized_name", "role"],
        unique=False,
    )
    op.create_table(
        "sources",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("agency", sa.String(length=300), nullable=False),
        sa.Column("jurisdiction", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("access_method", sa.String(length=40), nullable=False),
        sa.Column("update_frequency", sa.String(length=80), nullable=True),
        sa.Column("requires_authentication", sa.Boolean(), nullable=False),
        sa.Column("authentication_notes", sa.Text(), nullable=True),
        sa.Column("rate_limit_per_second", sa.Float(), nullable=True),
        sa.Column("rate_limit_notes", sa.Text(), nullable=True),
        sa.Column("license_name", sa.String(length=200), nullable=True),
        sa.Column("license_url", sa.Text(), nullable=True),
        sa.Column("licensing_notes", sa.Text(), nullable=True),
        sa.Column("attribution_required", sa.Boolean(), nullable=False),
        sa.Column("attribution_text", sa.Text(), nullable=True),
        sa.Column("robots_policy_status", sa.String(length=60), nullable=True),
        sa.Column("robots_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms_of_service_url", sa.Text(), nullable=True),
        sa.Column("geographic_coverage", sa.Text(), nullable=True),
        sa.Column("historical_coverage", sa.Text(), nullable=True),
        sa.Column("contains_personal_data", sa.Boolean(), nullable=False),
        sa.Column("reliability_score", sa.Float(), nullable=True),
        sa.Column("known_schema_issues", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reliability_score IS NULL OR (reliability_score >= 0 AND reliability_score <= 1)",
            name=op.f("ck_sources_reliability_score_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("slug", name=op.f("uq_sources_slug")),
    )
    op.create_index(op.f("ix_sources_category"), "sources", ["category"], unique=False)
    op.create_index(
        "ix_sources_jurisdiction_category", "sources", ["jurisdiction", "category"], unique=False
    )
    op.create_table(
        "organization_aliases",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(length=400), nullable=False),
        sa.Column("normalized_alias", sa.String(length=400), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_aliases_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_organization_aliases_source_id_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_aliases")),
        sa.UniqueConstraint(
            "organization_id", "normalized_alias", name="organization_alias_unique"
        ),
    )
    op.create_index(
        op.f("ix_organization_aliases_normalized_alias"),
        "organization_aliases",
        ["normalized_alias"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_aliases_organization_id"),
        "organization_aliases",
        ["organization_id"],
        unique=False,
    )
    op.create_geospatial_table(
        "sites",
        sa.Column("project_code", sa.String(length=60), nullable=False),
        sa.Column("display_name", sa.String(length=300), nullable=True),
        sa.Column("site_kind", sa.String(length=40), nullable=False),
        sa.Column("site_kind_assertion", sa.String(length=20), nullable=False),
        sa.Column("jurisdiction", sa.String(length=120), nullable=True),
        sa.Column("county", sa.String(length=80), nullable=False),
        sa.Column("region_slug", sa.String(length=80), nullable=False),
        sa.Column("current_stage", sa.SmallInteger(), nullable=False),
        sa.Column("current_confidence", sa.Float(), nullable=False),
        sa.Column("stage_last_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_last_calculated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("operator_organization_id", sa.UUID(), nullable=True),
        sa.Column("operator_assertion", sa.String(length=20), nullable=False),
        sa.Column("first_signal_date", sa.Date(), nullable=True),
        sa.Column("latest_signal_date", sa.Date(), nullable=True),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("total_acres", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column(
            "boundary",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "centroid",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_confidence >= 0 AND current_confidence <= 100",
            name=op.f("ck_sites_site_confidence_range"),
        ),
        sa.CheckConstraint(
            "current_stage >= 0 AND current_stage <= 8", name=op.f("ck_sites_stage_range")
        ),
        sa.ForeignKeyConstraint(
            ["operator_organization_id"],
            ["organizations.id"],
            name=op.f("fk_sites_operator_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
        sa.UniqueConstraint("project_code", name=op.f("uq_sites_project_code")),
    )
    op.create_geospatial_index(
        "ix_sites_boundary",
        "sites",
        ["boundary"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "ix_sites_centroid",
        "sites",
        ["centroid"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_sites_current_stage"), "sites", ["current_stage"], unique=False)
    op.create_index(
        op.f("ix_sites_first_signal_date"), "sites", ["first_signal_date"], unique=False
    )
    op.create_index(op.f("ix_sites_jurisdiction"), "sites", ["jurisdiction"], unique=False)
    op.create_index(
        op.f("ix_sites_latest_signal_date"), "sites", ["latest_signal_date"], unique=False
    )
    op.create_index(op.f("ix_sites_region_slug"), "sites", ["region_slug"], unique=False)
    op.create_index(
        "ix_sites_region_stage", "sites", ["region_slug", "current_stage"], unique=False
    )
    op.create_table(
        "source_connectors",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("entry_point", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("connector_version", sa.String(length=30), nullable=False),
        sa.Column("parser_version", sa.String(length=30), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule_cron", sa.String(length=80), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_field_signature", sa.String(length=64), nullable=True),
        sa.Column("access_limitation", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_source_connectors_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_connectors")),
        sa.UniqueConstraint("slug", name=op.f("uq_source_connectors_slug")),
    )
    op.create_index(
        op.f("ix_source_connectors_source_id"), "source_connectors", ["source_id"], unique=False
    )
    op.create_table(
        "source_documents",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_native_id", sa.String(length=300), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("document_type", sa.String(length=80), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("published_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parent_document_id", sa.UUID(), nullable=True),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column("version_count", sa.Integer(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_document_id"],
            ["source_documents.id"],
            name=op.f("fk_source_documents_parent_document_id_source_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_source_documents_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint("source_id", "source_native_id", name="source_native_id_unique"),
    )
    op.create_index(
        op.f("ix_source_documents_document_type"),
        "source_documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_documents_effective_date"),
        "source_documents",
        ["effective_date"],
        unique=False,
    )
    op.create_index(
        "ix_source_documents_published",
        "source_documents",
        ["source_id", "published_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_documents_published_date"),
        "source_documents",
        ["published_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_documents_source_id"), "source_documents", ["source_id"], unique=False
    )
    op.create_table(
        "connector_runs",
        sa.Column("connector_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("trigger", sa.String(length=30), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("items_discovered", sa.Integer(), nullable=False),
        sa.Column("items_fetched", sa.Integer(), nullable=False),
        sa.Column("items_parsed", sa.Integer(), nullable=False),
        sa.Column("items_normalized", sa.Integer(), nullable=False),
        sa.Column("items_rejected", sa.Integer(), nullable=False),
        sa.Column("items_unchanged", sa.Integer(), nullable=False),
        sa.Column("documents_created", sa.Integer(), nullable=False),
        sa.Column("versions_created", sa.Integer(), nullable=False),
        sa.Column("evidence_created", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("bytes_fetched", sa.BigInteger(), nullable=False),
        sa.Column(
            "http_status_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("error_categories", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_drift_detected", sa.Boolean(), nullable=False),
        sa.Column("field_signature", sa.String(length=64), nullable=True),
        sa.Column("connector_version", sa.String(length=30), nullable=True),
        sa.Column("parser_version", sa.String(length=30), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_connector_runs_run_finishes_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["source_connectors.id"],
            name=op.f("fk_connector_runs_connector_id_source_connectors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_runs")),
    )
    op.create_index(
        op.f("ix_connector_runs_connector_id"), "connector_runs", ["connector_id"], unique=False
    )
    op.create_index(
        "ix_connector_runs_connector_started",
        "connector_runs",
        ["connector_id", "started_at"],
        unique=False,
    )
    op.create_geospatial_table(
        "parcels",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("apn", sa.String(length=40), nullable=False),
        sa.Column("apn_formatted", sa.String(length=40), nullable=True),
        sa.Column("county", sa.String(length=80), nullable=False),
        sa.Column("jurisdiction", sa.String(length=120), nullable=True),
        sa.Column("situs_address", sa.Text(), nullable=True),
        sa.Column("situs_city", sa.String(length=120), nullable=True),
        sa.Column("situs_postal_code", sa.String(length=20), nullable=True),
        sa.Column("owner_name_raw", sa.String(length=400), nullable=True),
        sa.Column("owner_organization_id", sa.UUID(), nullable=True),
        sa.Column("owner_is_redacted", sa.Boolean(), nullable=False),
        sa.Column("land_use_code", sa.String(length=20), nullable=True),
        sa.Column("land_use_description", sa.String(length=200), nullable=True),
        sa.Column("legal_class_code", sa.String(length=20), nullable=True),
        sa.Column("lot_size_acres", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("lot_size_sqft", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("construction_year", sa.SmallInteger(), nullable=True),
        sa.Column("last_deed_number", sa.String(length=60), nullable=True),
        sa.Column("last_deed_date", sa.Date(), nullable=True),
        sa.Column("last_deed_url", sa.Text(), nullable=True),
        sa.Column("last_sale_date", sa.Date(), nullable=True),
        sa.Column("last_sale_price", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("assessor_url", sa.Text(), nullable=True),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "centroid",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lot_size_acres IS NULL OR lot_size_acres >= 0",
            name=op.f("ck_parcels_lot_size_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"],
            ["organizations.id"],
            name=op.f("fk_parcels_owner_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_parcels_source_document_id_source_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_parcels_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parcels")),
        sa.UniqueConstraint("source_id", "apn", name="parcel_apn_unique"),
    )
    op.create_index(op.f("ix_parcels_apn"), "parcels", ["apn"], unique=False)
    op.create_geospatial_index(
        "ix_parcels_centroid",
        "parcels",
        ["centroid"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "ix_parcels_city_use", "parcels", ["situs_city", "land_use_description"], unique=False
    )
    op.create_geospatial_index(
        "ix_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_parcels_jurisdiction"), "parcels", ["jurisdiction"], unique=False)
    op.create_index(op.f("ix_parcels_land_use_code"), "parcels", ["land_use_code"], unique=False)
    op.create_index(
        op.f("ix_parcels_land_use_description"), "parcels", ["land_use_description"], unique=False
    )
    op.create_index(op.f("ix_parcels_last_deed_date"), "parcels", ["last_deed_date"], unique=False)
    op.create_index(op.f("ix_parcels_last_sale_date"), "parcels", ["last_sale_date"], unique=False)
    op.create_index(op.f("ix_parcels_lot_size_acres"), "parcels", ["lot_size_acres"], unique=False)
    op.create_index(
        op.f("ix_parcels_owner_organization_id"), "parcels", ["owner_organization_id"], unique=False
    )
    op.create_index(op.f("ix_parcels_situs_city"), "parcels", ["situs_city"], unique=False)
    op.create_index(op.f("ix_parcels_source_id"), "parcels", ["source_id"], unique=False)
    op.create_table(
        "predictions",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("prediction_type", sa.String(length=40), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("predicted_stage", sa.SmallInteger(), nullable=True),
        sa.Column("raw_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confidence_band", sa.String(length=20), nullable=False),
        sa.Column("positive_contribution", sa.Float(), nullable=False),
        sa.Column("negative_contribution", sa.Float(), nullable=False),
        sa.Column("evidence_considered", sa.Integer(), nullable=False),
        sa.Column("distinct_evidence_kinds", sa.Integer(), nullable=False),
        sa.Column("is_backtest", sa.Boolean(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 100",
            name=op.f("ck_predictions_prediction_conf_range"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_predictions_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_predictions_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
    )
    op.create_index(op.f("ix_predictions_as_of_date"), "predictions", ["as_of_date"], unique=False)
    op.create_index(
        op.f("ix_predictions_model_version_id"), "predictions", ["model_version_id"], unique=False
    )
    op.create_index(
        "ix_predictions_site_calculated", "predictions", ["site_id", "calculated_at"], unique=False
    )
    op.create_index(op.f("ix_predictions_site_id"), "predictions", ["site_id"], unique=False)
    op.create_table(
        "site_estimates",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("estimate_type", sa.String(length=60), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("lower_value", sa.Float(), nullable=True),
        sa.Column("likely_value", sa.Float(), nullable=True),
        sa.Column("upper_value", sa.Float(), nullable=True),
        sa.Column("method", sa.String(length=120), nullable=False),
        sa.Column("assertion_class", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_record_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_site_estimates_estimate_confidence_range"),
        ),
        sa.CheckConstraint(
            "lower_value IS NULL OR upper_value IS NULL OR lower_value <= upper_value",
            name=op.f("ck_site_estimates_estimate_bounds_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_site_estimates_model_version_id_model_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_site_estimates_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_estimates")),
    )
    op.create_index(
        op.f("ix_site_estimates_estimate_type"), "site_estimates", ["estimate_type"], unique=False
    )
    op.create_index(op.f("ix_site_estimates_site_id"), "site_estimates", ["site_id"], unique=False)
    op.create_table(
        "site_stage_history",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("from_stage", sa.SmallInteger(), nullable=True),
        sa.Column("to_stage", sa.SmallInteger(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_downgrade", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "triggering_evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("model_version_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_stage IS NULL OR (from_stage >= 0 AND from_stage <= 8)",
            name=op.f("ck_site_stage_history_from_stage_range"),
        ),
        sa.CheckConstraint(
            "to_stage >= 0 AND to_stage <= 8", name=op.f("ck_site_stage_history_to_stage_range")
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_site_stage_history_model_version_id_model_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_site_stage_history_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_stage_history")),
    )
    op.create_index(
        op.f("ix_site_stage_history_effective_date"),
        "site_stage_history",
        ["effective_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_stage_history_site_id"), "site_stage_history", ["site_id"], unique=False
    )
    op.create_index(
        "ix_stage_history_site_effective",
        "site_stage_history",
        ["site_id", "effective_date"],
        unique=False,
    )
    op.create_geospatial_table(
        "substations",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_native_id", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("operator_name", sa.String(length=300), nullable=True),
        sa.Column("operator_organization_id", sa.UUID(), nullable=True),
        sa.Column("max_voltage_kv", sa.Float(), nullable=True),
        sa.Column("voltages_kv", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("substation_function", sa.String(length=60), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "location",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operator_organization_id"],
            ["organizations.id"],
            name=op.f("fk_substations_operator_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_substations_source_document_id_source_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_substations_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_substations")),
        sa.UniqueConstraint("source_id", "source_native_id", name="substation_native_unique"),
    )
    op.create_geospatial_index(
        "ix_substations_geometry",
        "substations",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "ix_substations_location",
        "substations",
        ["location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_substations_max_voltage_kv"), "substations", ["max_voltage_kv"], unique=False
    )
    op.create_index(op.f("ix_substations_name"), "substations", ["name"], unique=False)
    op.create_index(
        op.f("ix_substations_operator_name"), "substations", ["operator_name"], unique=False
    )
    op.create_index(op.f("ix_substations_source_id"), "substations", ["source_id"], unique=False)
    op.create_geospatial_table(
        "transmission_lines",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_native_id", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("operator_name", sa.String(length=300), nullable=True),
        sa.Column("voltage_kv", sa.Float(), nullable=True),
        sa.Column("circuit_count", sa.SmallInteger(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="MULTILINESTRING",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_transmission_lines_source_document_id_source_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_transmission_lines_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transmission_lines")),
        sa.UniqueConstraint("source_id", "source_native_id", name="transmission_native_unique"),
    )
    op.create_geospatial_index(
        "ix_transmission_lines_geometry",
        "transmission_lines",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_transmission_lines_operator_name"),
        "transmission_lines",
        ["operator_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transmission_lines_source_id"), "transmission_lines", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_transmission_lines_voltage_kv"), "transmission_lines", ["voltage_kv"], unique=False
    )
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("content_length", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("storage_backend", sa.String(length=20), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("http_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("etag", sa.String(length=300), nullable=True),
        sa.Column("last_modified", sa.String(length=120), nullable=True),
        sa.Column("connector_version", sa.String(length=30), nullable=True),
        sa.Column("parser_version", sa.String(length=30), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("supersedes_version_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_length >= 0", name=op.f("ck_document_versions_content_length_non_negative")
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_document_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
            name=op.f("fk_document_versions_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["connector_runs.id"],
            name=op.f("fk_document_versions_run_id_connector_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"],
            ["document_versions.id"],
            name=op.f("fk_document_versions_supersedes_version_id_document_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint("document_id", "content_sha256", name="document_content_unique"),
        sa.UniqueConstraint("document_id", "version_number", name="document_version_number_unique"),
    )
    op.create_index(
        op.f("ix_document_versions_content_sha256"),
        "document_versions",
        ["content_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    op.create_index(
        "ix_document_versions_retrieved",
        "document_versions",
        ["document_id", "retrieved_at"],
        unique=False,
    )
    op.create_table(
        "ingestion_failures",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("error_category", sa.String(length=60), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_native_id", sa.String(length=200), nullable=True),
        sa.Column("payload_excerpt", sa.Text(), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["connector_runs.id"],
            name=op.f("fk_ingestion_failures_run_id_connector_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_failures")),
    )
    op.create_index(
        op.f("ix_ingestion_failures_error_category"),
        "ingestion_failures",
        ["error_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_failures_run_id"), "ingestion_failures", ["run_id"], unique=False
    )
    op.create_geospatial_table(
        "permits",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_native_id", sa.String(length=200), nullable=False),
        sa.Column("permit_number", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("permit_type_raw", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=120), nullable=True),
        sa.Column("issuing_authority", sa.String(length=200), nullable=True),
        sa.Column("jurisdiction", sa.String(length=120), nullable=True),
        sa.Column("applied_date", sa.Date(), nullable=True),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("status_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("address_raw", sa.Text(), nullable=True),
        sa.Column("parcel_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("applicant_organization_id", sa.UUID(), nullable=True),
        sa.Column(
            "location",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("valuation", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["applicant_organization_id"],
            ["organizations.id"],
            name=op.f("fk_permits_applicant_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["parcels.id"],
            name=op.f("fk_permits_parcel_id_parcels"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_permits_site_id_sites"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_permits_source_document_id_source_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_permits_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permits")),
        sa.UniqueConstraint("source_id", "source_native_id", name="permit_native_unique"),
    )
    op.create_index(op.f("ix_permits_applied_date"), "permits", ["applied_date"], unique=False)
    op.create_index(op.f("ix_permits_category"), "permits", ["category"], unique=False)
    op.create_index(
        "ix_permits_category_issued", "permits", ["category", "issued_date"], unique=False
    )
    op.create_index(op.f("ix_permits_issued_date"), "permits", ["issued_date"], unique=False)
    op.create_index(op.f("ix_permits_jurisdiction"), "permits", ["jurisdiction"], unique=False)
    op.create_geospatial_index(
        "ix_permits_location",
        "permits",
        ["location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_permits_parcel_id"), "permits", ["parcel_id"], unique=False)
    op.create_index(op.f("ix_permits_permit_number"), "permits", ["permit_number"], unique=False)
    op.create_index(op.f("ix_permits_site_id"), "permits", ["site_id"], unique=False)
    op.create_index(op.f("ix_permits_source_id"), "permits", ["source_id"], unique=False)
    op.create_table(
        "site_parcel_links",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("parcel_id", sa.UUID(), nullable=False),
        sa.Column("link_reason", sa.String(length=60), nullable=False),
        sa.Column("match_method", sa.String(length=40), nullable=False),
        sa.Column("spatial_confidence", sa.Float(), nullable=True),
        sa.Column("distance_meters", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("human_review_status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("effective_start", sa.Date(), nullable=True),
        sa.Column("effective_end", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_site_parcel_links_link_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["parcels.id"],
            name=op.f("fk_site_parcel_links_parcel_id_parcels"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_site_parcel_links_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_parcel_links")),
        sa.UniqueConstraint("site_id", "parcel_id", name="site_parcel_unique"),
    )
    op.create_index(
        op.f("ix_site_parcel_links_effective_end"),
        "site_parcel_links",
        ["effective_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_parcel_links_effective_start"),
        "site_parcel_links",
        ["effective_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_parcel_links_parcel_id"), "site_parcel_links", ["parcel_id"], unique=False
    )
    op.create_index(
        op.f("ix_site_parcel_links_site_id"), "site_parcel_links", ["site_id"], unique=False
    )
    op.create_table(
        "evidence_records",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("parcel_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("evidence_kind", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("snippet_start_offset", sa.Integer(), nullable=True),
        sa.Column("snippet_end_offset", sa.Integer(), nullable=True),
        sa.Column("snippet_locator", sa.String(length=200), nullable=True),
        sa.Column("observed_at", sa.Date(), nullable=False),
        sa.Column("assertion_class", sa.String(length=20), nullable=False),
        sa.Column("extraction_method", sa.String(length=40), nullable=False),
        sa.Column("polarity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("parser_version", sa.String(length=30), nullable=False),
        sa.Column("human_review_status", sa.String(length=30), nullable=False),
        sa.Column("normalized_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_evidence_records_confidence_range")
        ),
        sa.CheckConstraint(
            "snippet_end_offset IS NULL OR snippet_start_offset IS NULL OR snippet_end_offset >= snippet_start_offset",
            name=op.f("ck_evidence_records_snippet_offsets_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
            name=op.f("fk_evidence_records_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_evidence_records_document_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidence_records_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["parcels.id"],
            name=op.f("fk_evidence_records_parcel_id_parcels"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_evidence_records_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_records")),
    )
    op.create_index(
        "ix_evidence_kind_observed",
        "evidence_records",
        ["evidence_kind", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_records_document_id"), "evidence_records", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_records_document_version_id"),
        "evidence_records",
        ["document_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_records_evidence_kind"),
        "evidence_records",
        ["evidence_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_records_observed_at"), "evidence_records", ["observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_records_organization_id"),
        "evidence_records",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_records_parcel_id"), "evidence_records", ["parcel_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_records_site_id"), "evidence_records", ["site_id"], unique=False
    )
    op.create_index(
        "ix_evidence_site_observed", "evidence_records", ["site_id", "observed_at"], unique=False
    )
    op.create_table(
        "infrastructure_dependencies",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("infrastructure_kind", sa.String(length=40), nullable=False),
        sa.Column("substation_id", sa.UUID(), nullable=True),
        sa.Column("transmission_line_id", sa.UUID(), nullable=True),
        sa.Column("permit_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("dependency_status", sa.String(length=40), nullable=False),
        sa.Column("is_blocking", sa.Boolean(), nullable=False),
        sa.Column("match_method", sa.String(length=40), nullable=True),
        sa.Column("distance_meters", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("assertion_class", sa.String(length=20), nullable=False),
        sa.Column("evidence_record_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_infrastructure_dependencies_dependency_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["evidence_records.id"],
            name=op.f("fk_infrastructure_dependencies_evidence_record_id_evidence_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["permit_id"],
            ["permits.id"],
            name=op.f("fk_infrastructure_dependencies_permit_id_permits"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_infrastructure_dependencies_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["substation_id"],
            ["substations.id"],
            name=op.f("fk_infrastructure_dependencies_substation_id_substations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["transmission_line_id"],
            ["transmission_lines.id"],
            name=op.f("fk_infrastructure_dependencies_transmission_line_id_transmission_lines"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_infrastructure_dependencies")),
    )
    op.create_index(
        "ix_dependencies_site_kind",
        "infrastructure_dependencies",
        ["site_id", "infrastructure_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_infrastructure_dependencies_site_id"),
        "infrastructure_dependencies",
        ["site_id"],
        unique=False,
    )
    op.create_table(
        "organization_relationships",
        sa.Column("from_organization_id", sa.UUID(), nullable=False),
        sa.Column("to_organization_id", sa.UUID(), nullable=False),
        sa.Column("relationship_type", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("assertion_class", sa.String(length=20), nullable=False),
        sa.Column("extraction_method", sa.String(length=40), nullable=False),
        sa.Column("human_review_status", sa.String(length=30), nullable=False),
        sa.Column("evidence_record_id", sa.UUID(), nullable=True),
        sa.Column("supporting_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "contradicting_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("effective_start", sa.Date(), nullable=True),
        sa.Column("effective_end", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_organization_relationships_rel_confidence_range"),
        ),
        sa.CheckConstraint(
            "from_organization_id <> to_organization_id",
            name=op.f("ck_organization_relationships_no_self_relationship"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["evidence_records.id"],
            name=op.f("fk_organization_relationships_evidence_record_id_evidence_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_relationships_from_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_relationships_to_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_relationships")),
        sa.UniqueConstraint(
            "from_organization_id",
            "to_organization_id",
            "relationship_type",
            "effective_start",
            name="organization_relationship_unique",
        ),
    )
    op.create_index(
        op.f("ix_organization_relationships_effective_end"),
        "organization_relationships",
        ["effective_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_relationships_effective_start"),
        "organization_relationships",
        ["effective_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_relationships_from_organization_id"),
        "organization_relationships",
        ["from_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_relationships_relationship_type"),
        "organization_relationships",
        ["relationship_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_relationships_to_organization_id"),
        "organization_relationships",
        ["to_organization_id"],
        unique=False,
    )
    op.create_table(
        "parcel_ownership_events",
        sa.Column("parcel_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("owner_name_raw", sa.String(length=400), nullable=True),
        sa.Column("owner_is_redacted", sa.Boolean(), nullable=False),
        sa.Column("deed_number", sa.String(length=60), nullable=True),
        sa.Column("deed_url", sa.Text(), nullable=True),
        sa.Column("sale_price", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("assertion_class", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_record_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_parcel_ownership_events_ownership_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["evidence_records.id"],
            name=op.f("fk_parcel_ownership_events_evidence_record_id_evidence_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_parcel_ownership_events_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["parcels.id"],
            name=op.f("fk_parcel_ownership_events_parcel_id_parcels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parcel_ownership_events")),
        sa.UniqueConstraint(
            "parcel_id", "event_date", "deed_number", name="parcel_ownership_event_unique"
        ),
    )
    op.create_index(
        op.f("ix_parcel_ownership_events_event_date"),
        "parcel_ownership_events",
        ["event_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parcel_ownership_events_organization_id"),
        "parcel_ownership_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parcel_ownership_events_parcel_id"),
        "parcel_ownership_events",
        ["parcel_id"],
        unique=False,
    )
    op.create_table(
        "prediction_explanations",
        sa.Column("prediction_id", sa.UUID(), nullable=False),
        sa.Column("evidence_record_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.String(length=80), nullable=False),
        sa.Column("evidence_kind", sa.String(length=80), nullable=True),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("base_weight", sa.Float(), nullable=False),
        sa.Column("applied_weight", sa.Float(), nullable=False),
        sa.Column("confidence_multiplier", sa.Float(), nullable=False),
        sa.Column("recency_multiplier", sa.Float(), nullable=False),
        sa.Column("polarity", sa.String(length=20), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["evidence_records.id"],
            name=op.f("fk_prediction_explanations_evidence_record_id_evidence_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
            name=op.f("fk_prediction_explanations_prediction_id_predictions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prediction_explanations")),
    )
    op.create_index(
        op.f("ix_prediction_explanations_evidence_record_id"),
        "prediction_explanations",
        ["evidence_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_explanations_prediction_id"),
        "prediction_explanations",
        ["prediction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_prediction_explanations_prediction_id"), table_name="prediction_explanations"
    )
    op.drop_index(
        op.f("ix_prediction_explanations_evidence_record_id"), table_name="prediction_explanations"
    )
    op.drop_table("prediction_explanations")
    op.drop_index(
        op.f("ix_parcel_ownership_events_parcel_id"), table_name="parcel_ownership_events"
    )
    op.drop_index(
        op.f("ix_parcel_ownership_events_organization_id"), table_name="parcel_ownership_events"
    )
    op.drop_index(
        op.f("ix_parcel_ownership_events_event_date"), table_name="parcel_ownership_events"
    )
    op.drop_table("parcel_ownership_events")
    op.drop_index(
        op.f("ix_organization_relationships_to_organization_id"),
        table_name="organization_relationships",
    )
    op.drop_index(
        op.f("ix_organization_relationships_relationship_type"),
        table_name="organization_relationships",
    )
    op.drop_index(
        op.f("ix_organization_relationships_from_organization_id"),
        table_name="organization_relationships",
    )
    op.drop_index(
        op.f("ix_organization_relationships_effective_start"),
        table_name="organization_relationships",
    )
    op.drop_index(
        op.f("ix_organization_relationships_effective_end"), table_name="organization_relationships"
    )
    op.drop_table("organization_relationships")
    op.drop_index(
        op.f("ix_infrastructure_dependencies_site_id"), table_name="infrastructure_dependencies"
    )
    op.drop_index("ix_dependencies_site_kind", table_name="infrastructure_dependencies")
    op.drop_table("infrastructure_dependencies")
    op.drop_index("ix_evidence_site_observed", table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_site_id"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_parcel_id"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_organization_id"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_observed_at"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_evidence_kind"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_document_version_id"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_document_id"), table_name="evidence_records")
    op.drop_index("ix_evidence_kind_observed", table_name="evidence_records")
    op.drop_table("evidence_records")
    op.drop_index(op.f("ix_site_parcel_links_site_id"), table_name="site_parcel_links")
    op.drop_index(op.f("ix_site_parcel_links_parcel_id"), table_name="site_parcel_links")
    op.drop_index(op.f("ix_site_parcel_links_effective_start"), table_name="site_parcel_links")
    op.drop_index(op.f("ix_site_parcel_links_effective_end"), table_name="site_parcel_links")
    op.drop_table("site_parcel_links")
    op.drop_index(op.f("ix_permits_source_id"), table_name="permits")
    op.drop_index(op.f("ix_permits_site_id"), table_name="permits")
    op.drop_index(op.f("ix_permits_permit_number"), table_name="permits")
    op.drop_index(op.f("ix_permits_parcel_id"), table_name="permits")
    op.drop_geospatial_index(
        "ix_permits_location", table_name="permits", postgresql_using="gist", column_name="location"
    )
    op.drop_index(op.f("ix_permits_jurisdiction"), table_name="permits")
    op.drop_index(op.f("ix_permits_issued_date"), table_name="permits")
    op.drop_index("ix_permits_category_issued", table_name="permits")
    op.drop_index(op.f("ix_permits_category"), table_name="permits")
    op.drop_index(op.f("ix_permits_applied_date"), table_name="permits")
    op.drop_geospatial_table("permits")
    op.drop_index(op.f("ix_ingestion_failures_run_id"), table_name="ingestion_failures")
    op.drop_index(op.f("ix_ingestion_failures_error_category"), table_name="ingestion_failures")
    op.drop_table("ingestion_failures")
    op.drop_index("ix_document_versions_retrieved", table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_content_sha256"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_transmission_lines_voltage_kv"), table_name="transmission_lines")
    op.drop_index(op.f("ix_transmission_lines_source_id"), table_name="transmission_lines")
    op.drop_index(op.f("ix_transmission_lines_operator_name"), table_name="transmission_lines")
    op.drop_geospatial_index(
        "ix_transmission_lines_geometry",
        table_name="transmission_lines",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("transmission_lines")
    op.drop_index(op.f("ix_substations_source_id"), table_name="substations")
    op.drop_index(op.f("ix_substations_operator_name"), table_name="substations")
    op.drop_index(op.f("ix_substations_name"), table_name="substations")
    op.drop_index(op.f("ix_substations_max_voltage_kv"), table_name="substations")
    op.drop_geospatial_index(
        "ix_substations_location",
        table_name="substations",
        postgresql_using="gist",
        column_name="location",
    )
    op.drop_geospatial_index(
        "ix_substations_geometry",
        table_name="substations",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("substations")
    op.drop_index("ix_stage_history_site_effective", table_name="site_stage_history")
    op.drop_index(op.f("ix_site_stage_history_site_id"), table_name="site_stage_history")
    op.drop_index(op.f("ix_site_stage_history_effective_date"), table_name="site_stage_history")
    op.drop_table("site_stage_history")
    op.drop_index(op.f("ix_site_estimates_site_id"), table_name="site_estimates")
    op.drop_index(op.f("ix_site_estimates_estimate_type"), table_name="site_estimates")
    op.drop_table("site_estimates")
    op.drop_index(op.f("ix_predictions_site_id"), table_name="predictions")
    op.drop_index("ix_predictions_site_calculated", table_name="predictions")
    op.drop_index(op.f("ix_predictions_model_version_id"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_as_of_date"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_index(op.f("ix_parcels_source_id"), table_name="parcels")
    op.drop_index(op.f("ix_parcels_situs_city"), table_name="parcels")
    op.drop_index(op.f("ix_parcels_owner_organization_id"), table_name="parcels")
    op.drop_index(op.f("ix_parcels_lot_size_acres"), table_name="parcels")
    op.drop_index(op.f("ix_parcels_last_sale_date"), table_name="parcels")
    op.drop_index(op.f("ix_parcels_last_deed_date"), table_name="parcels")
    op.drop_index(op.f("ix_parcels_land_use_description"), table_name="parcels")
    op.drop_index(op.f("ix_parcels_land_use_code"), table_name="parcels")
    op.drop_index(op.f("ix_parcels_jurisdiction"), table_name="parcels")
    op.drop_geospatial_index(
        "ix_parcels_geometry", table_name="parcels", postgresql_using="gist", column_name="geometry"
    )
    op.drop_index("ix_parcels_city_use", table_name="parcels")
    op.drop_geospatial_index(
        "ix_parcels_centroid", table_name="parcels", postgresql_using="gist", column_name="centroid"
    )
    op.drop_index(op.f("ix_parcels_apn"), table_name="parcels")
    op.drop_geospatial_table("parcels")
    op.drop_index("ix_connector_runs_connector_started", table_name="connector_runs")
    op.drop_index(op.f("ix_connector_runs_connector_id"), table_name="connector_runs")
    op.drop_table("connector_runs")
    op.drop_index(op.f("ix_source_documents_source_id"), table_name="source_documents")
    op.drop_index(op.f("ix_source_documents_published_date"), table_name="source_documents")
    op.drop_index("ix_source_documents_published", table_name="source_documents")
    op.drop_index(op.f("ix_source_documents_effective_date"), table_name="source_documents")
    op.drop_index(op.f("ix_source_documents_document_type"), table_name="source_documents")
    op.drop_table("source_documents")
    op.drop_index(op.f("ix_source_connectors_source_id"), table_name="source_connectors")
    op.drop_table("source_connectors")
    op.drop_index("ix_sites_region_stage", table_name="sites")
    op.drop_index(op.f("ix_sites_region_slug"), table_name="sites")
    op.drop_index(op.f("ix_sites_latest_signal_date"), table_name="sites")
    op.drop_index(op.f("ix_sites_jurisdiction"), table_name="sites")
    op.drop_index(op.f("ix_sites_first_signal_date"), table_name="sites")
    op.drop_index(op.f("ix_sites_current_stage"), table_name="sites")
    op.drop_geospatial_index(
        "ix_sites_centroid", table_name="sites", postgresql_using="gist", column_name="centroid"
    )
    op.drop_geospatial_index(
        "ix_sites_boundary", table_name="sites", postgresql_using="gist", column_name="boundary"
    )
    op.drop_geospatial_table("sites")
    op.drop_index(
        op.f("ix_organization_aliases_organization_id"), table_name="organization_aliases"
    )
    op.drop_index(
        op.f("ix_organization_aliases_normalized_alias"), table_name="organization_aliases"
    )
    op.drop_table("organization_aliases")
    op.drop_index("ix_sources_jurisdiction_category", table_name="sources")
    op.drop_index(op.f("ix_sources_category"), table_name="sources")
    op.drop_table("sources")
    op.drop_index("ix_organizations_normalized_role", table_name="organizations")
    op.drop_index(op.f("ix_organizations_normalized_name"), table_name="organizations")
    op.drop_index(
        "ix_organizations_name_trgm",
        table_name="organizations",
        postgresql_using="gin",
        postgresql_ops={"normalized_name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_organizations_canonical_name"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_human_reviews_target_table"), table_name="human_reviews")
    op.drop_index(op.f("ix_human_reviews_target_id"), table_name="human_reviews")
    op.drop_index("ix_human_reviews_target", table_name="human_reviews")
    op.drop_table("human_reviews")
    # ### end Alembic commands ###
